### PR TITLE
Fix #288 Bluetooth MAC

### LINKED ISSUE #288: Bluetooth address not getting properly set
I've noticed that when I take a brand new Pi 3B+ and boot it with hypriotos, without having booted with raspbian previously, the bluetooth address for the Pi is always `43:45:c0:00:1f:ac`

This caught me off guard so I did a bit of searching, and from what I can find, there's a step that raspbian performs on first boot which sets the bluetooth address in OTP memory based on the serial number.  You can see reference to how this is calculate in this isssue

https://github.com/agherzan/meta-raspberrypi/issues/236

Is it possible for HypriotOS to also perform this OTP update or must I always first boot with raspbian before booting hypriotos on a brand new pi?

### PR DESCRIPTION
**Pull request by ProfFan**

### CODE REVIEW

**Comment by StefanScherer** [comment]
Thanks @ProfFan 
Do you know if that works only with the built-in bluetooth, or also with USB bluetooth sticks eg on a Raspberry Pi 2?

If someone wants to test this, here is the SD card image with that change: https://246-49221370-gh.circle-artifacts.com/0/home/circleci/project/output/hypriotos-rpi-dirty.img.zip

**Comment by ProfFan** [comment]
This is a fix for the internal Bluetooth, but the original one can only work with internal BT anyway :)

External USB sticks do not need this, as they have their own driver and their MAC should already be configured by that.

**Comment by ProfFan** [comment]
Note: a more proper fix would be have the same /dev/serial1 name in accordance with Raspbian, so we can just use their btuart script.

**Comment by StefanScherer** [comment]
Ok, let's merge this. Thanks again!

**Pull request merged**
